### ISSUE TITLE
A bunch of errors

### ISSUE THREAD

**Issue by MaddoScientisto** [ihavenoface/4chan-x#47] opened 2012-10-26 10:50 UTC
I clicked a cross thread link and BAM, got the following errors:

```
4chan X (2.36.1) error: node is null
Report the bug at ihavenoface.github.com/4chan-x/#bug-report

URL: https://boards.4chan.org/co/res/42180854#p42180854
Time.node@file:///C:/Users/Jack/AppData/Roaming/Mozilla/Firefox/Profiles/v87vn8ed.default/gm_scripts/4chan_x/4chan_x.user.js:3855
Main.node@file:///C:/Users/Jack/AppData/Roaming/Mozilla/Firefox/Profiles/v87vn8ed.default/gm_scripts/4chan_x/4chan_x.user.js:6155
Main.ready@file:///C:/Users/Jack/AppData/Roaming/Mozilla/Firefox/Profiles/v87vn8ed.default/gm_scripts/4chan_x/4chan_x.user.js:6096
.ready/cb@file:///C:/Users/Jack/AppData/Roaming/Mozilla/Firefox/Profiles/v87vn8ed.default/gm_scripts/4chan_x/4chan_x.user.js:338
```

```
4chan X (2.36.1) error: el is null
Report the bug at ihavenoface.github.com/4chan-x/#bug-report

URL: https://boards.4chan.org/co/res/42180854#p42180854
.on@file:///C:/Users/Jack/AppData/Roaming/Mozilla/Firefox/Profiles/v87vn8ed.default/gm_scripts/4chan_x/4chan_x.user.js:504
QR.node@file:///C:/Users/Jack/AppData/Roaming/Mozilla/Firefox/Profiles/v87vn8ed.default/gm_scripts/4chan_x/4chan_x.user.js:1914
Main.node@file:///C:/Users/Jack/AppData/Roaming/Mozilla/Firefox/Profiles/v87vn8ed.default/gm_scripts/4chan_x/4chan_x.user.js:6155
Main.ready@file:///C:/Users/Jack/AppData/Roaming/Mozilla/Firefox/Profiles/v87vn8ed.default/gm_scripts/4chan_x/4chan_x.user.js:6096
.ready/cb@file:///C:/Users/Jack/AppData/Roaming/Mozilla/Firefox/Profiles/v87vn8ed.default/gm_scripts/4chan_x/4chan_x.user.js:338
```

**Comment by ihavenoface** [comment] 2012-10-26 12:31
Since none of the parts I wrote for this fork is responsible for this it could take some time to identify the problem. More so since I don't seem able to reproduce this.
My guess is it's only something temporary (if anything) like https://github.com/aeosynth/4chan-x/pull/375 for instance.

**Comment by seaweedchan** [comment] 2012-10-26 15:05
@Jackomel What browser? Did you try a new profile? Has it happened since?

**Comment by vampiricwulf** [comment] 2012-10-27 03:19
Did you try re-installing 4chanx?
I notice that sometimes my scripts install broken and I have to reinstall for them to work.

**Comment by MaddoScientisto** [comment] 2012-10-27 08:57
sorry, it only happened  on my laptop and I haven't browsed 4chan since

**Comment by ihavenoface** [comment] 2012-10-28 14:00
If this happens again, please let me know.
Closing this for now.

**Comment by seaweedchan** [comment] 2012-10-29 12:32
Just happened for me.

```
4chan X (2.36.1) error: el is null
Report the bug at ihavenoface.github.com/4chan-x/#bug-report

URL: https://boards.4chan.org/g/
.on@file:///C:/Users/seaweed/AppData/Roaming/Mozilla/Firefox/Profiles/ogw1km7i.Default%20Userasd/gm_scripts/4chan_x/4chan_x.user.js:505
QR.node@file:///C:/Users/seaweed/AppData/Roaming/Mozilla/Firefox/Profiles/ogw1km7i.Default%20Userasd/gm_scripts/4chan_x/4chan_x.user.js:1910
Main.node@file:///C:/Users/seaweed/AppData/Roaming/Mozilla/Firefox/Profiles/ogw1km7i.Default%20Userasd/gm_scripts/4chan_x/4chan_x.user.js:6108
Main.ready@file:///C:/Users/seaweed/AppData/Roaming/Mozilla/Firefox/Profiles/ogw1km7i.Default%20Userasd/gm_scripts/4chan_x/4chan_x.user.js:6049
.ready/cb@file:///C:/Users/seaweed/AppData/Roaming/Mozilla/Firefox/Profiles/ogw1km7i.Default%20Userasd/gm_scripts/4chan_x/4chan_x.user.js:339
```

**Comment by ihavenoface** [comment] 2012-10-29 14:13
Then let me just speculate here → when the page loads the QR adds an event listener which observes when one clicks on a post-number and calls QR.quote, giving through the href of the anchor after doing so.
Now for some reason 4chan doesn't contain .post or it has been moved (on https maybe?) in which case I could readjust this thing in case of failure, so if this happens again, please run an inspector tool on a postnumber and give me the output.

**Comment by vampiricwulf** [comment] 2012-10-29 14:46
I remember getting that error, that's the one that got fixed when I re-installed 4chanx.

**Comment by seaweedchan** [comment] 2012-10-29 14:50
For reference I was testing something in AppChan X, disabled it, re-enabled ihavenoface X, and refreshed /g/ which was when I got the error.

**Comment by vampiricwulf** [comment] 2012-11-05 02:29
Oh look, it's randomly doing it to me:

```
4chan X (2.36.3) error: null has no properties
Report the bug at ihavenoface.github.com/4chan-x/#bug-report

URL: http://boards.4chan.org/a/
Linkify.text@file:///C:/Users/vampiricwulf/AppData/Roaming/Mozilla/Firefox/Profiles/tmgurhpw.default/gm_scripts/4chan_x/4chan_x.user.js:5623
Linkify.node@file:///C:/Users/vampiricwulf/AppData/Roaming/Mozilla/Firefox/Profiles/tmgurhpw.default/gm_scripts/4chan_x/4chan_x.user.js:5593
Main.node@file:///C:/Users/vampiricwulf/AppData/Roaming/Mozilla/Firefox/Profiles/tmgurhpw.default/gm_scripts/4chan_x/4chan_x.user.js:6074
Main.ready@file:///C:/Users/vampiricwulf/AppData/Roaming/Mozilla/Firefox/Profiles/tmgurhpw.default/gm_scripts/4chan_x/4chan_x.user.js:6001
.ready/cb@file:///C:/Users/vampiricwulf/AppData/Roaming/Mozilla/Firefox/Profiles/tmgurhpw.default/gm_scripts/4chan_x/4chan_x.user.js:332
```

Reinstalled all my scripts and the bug is gone. *shrug*

**Comment by ihavenoface** [comment] 2012-11-05 08:00
Reinstalling will do exactly nothing at all.
I was be able to reproduce this yesterday however. I had the site loading and before it finished I did a refresh. Content that isn't loaded cannot be parsed so 4chan x starts throwing an error orginating from Main.ready and the position where it was able to do anything with the current loaded content at all.
The above lets me say that not the script but 4chan is at fault. Maybe I could look at Main and try to make it have less output, this would be my first time with try/catch/finally though.

**Comment by ihavenoface** [comment] 2012-11-05 11:30
No idea if this is the solution at all, but this should delay the error check later on so we don't report stuff that isn't even loaded.

1dce2eed838e71f38521c27704e9e2d671d3c467

**Comment by ramenchef** [comment] 2012-11-05 19:00
Uncaught TypeError: Cannot read property 'firstChild' of null
is the error in the console after turning on tampermonkey debug mode. (chrome dev channel)

**Comment by ihavenoface** [comment] 2012-11-05 21:49
@ramenchef 
Well this isn't really specific. Does 4chan x throw the error or what did you do to cause it? What version are you on?

**Comment by ramenchef** [comment] 2012-11-05 21:56
Sorry. This is happening with tampermonkey on chrome 24.0.1312.2 dev-m. 4chan X version is 2.36.3. I am getting an error popup when I visit /a/ on occasion (maybe 3-5% of the time. Reproduceable for 1-3 refreshes then goes away) Error is "FirstPost(?) is null" Problem is that the error is in a popup that I can't C&P from. Maybe I just don't know where tampermonkey records these errors. I use HTTPS if that helps.

**Comment by ihavenoface** [comment] 2012-11-05 22:08
Please try to visit this http://boards.4chan.org/vg/res/17860740 thread. If the error pops up again it is related to the modification I made to the Linkifier.

**Comment by ramenchef** [comment] 2012-11-05 22:11
Hmm, no errors when visiting that link. I'll try and type out the error the next time it happens.

**Comment by ihavenoface** [comment] 2012-11-05 22:12
Or just screenshot it?

**Comment by ramenchef** [comment] 2012-11-06 00:56
Here you go.http://i.imgur.com/tBvxb.png

**Comment by ihavenoface** [comment] 2012-11-06 10:00
Yup, that's related to #24.

**Closed as completed** 2012-11-15 18:08 UTC
Labels: 4chan
