### ISSUE TITLE
"Current" in custom board navigation broken in Firefox.

### ISSUE THREAD

**Issue by usernamestring** [ihavenoface/4chan-x#254] opened 2013-09-19 02:37 UTC
In the latest release, the "current" header option is broken in Firefox and is interpreted as a plain text string. On a fresh profile after installing Greasemonkey + 4chan X and visiting any board, the default header always reads "[current-title / +]".
Also links to certain boards like /k/ and /q/ in header bar won't work and are displayed as plain text.
I'm using Firefox version 24 with only Greasemonkey and 4chan X installed and there's nothing in the error console.

**Comment by ihavenoface** [comment] 2013-09-19 18:20
Not able to reproduce the issue.

> and /q/

/q/ was removed.

**Comment by usernamestring** [comment] 2013-09-30 08:15
Sorry, when I posted this /q/ was still up but board posting was disabled and the link to the board in the navigation bar was removed. This error only happened while in there and I hadn't noticed.
But the same bug is present at this moment at /con/, it seems like something breaks when visiting a board and its direct link isn't present in the boards list header or footer.

**Comment by ihavenoface** [comment] 2013-09-30 13:51
> it seems like something breaks when visiting a board and its direct link isn't present in the boards list header or footer.

Because we're fetching the info from the header. If it's not there it won't be available in the Rice section.

**Comment by ihavenoface** [comment] 2013-10-03 21:04
Closing since this issue seems to be non-existent.

**Closed as completed by ihavenoface** 2013-10-03 21:04 UTC
