### ISSUE TITLE
No worky at all

### ISSUE THREAD

**Issue by OrdinaryMagician** [ihavenoface/4chan-x#174] opened 2013-03-01 19:15 UTC
Since a while ago 4chan X no longer works properly. Only the configuration menu is accessible. The quick reply box disappeared completely, along with some of the elements at the top of the screen (post counts, autoupdater and all that)

4chan's downtime today probably has something to do with this problem.

**Comment by lucy** [comment] 2013-03-01 20:24
:1234:

**Comment by ihavenoface** [comment] 2013-03-01 21:35
Cannot reproduce.

How about some more information like your browser and version of the script you're using?

**Comment by ihavenoface** [comment] 2013-03-01 21:42
Looks like the've changed/removed the ads. Should be fixed with the new version, 0672b5fc79a24a21e5ef1d9dd884cc48279a5659

**Comment by lucy** [comment] 2013-03-01 21:43
yes, fixed in 2.38.5

**Closed as completed by ihavenoface** 2013-03-01 21:42 UTC

**Comment by smcdude** [comment] 2013-03-01 21:46
That fixed it.

**Comment by OrdinaryMagician** [comment] 2013-03-01 21:51
thank you
