### ISSUE TITLE
Linkifier slightly broken by an html change

### ISSUE THREAD

**Issue by kweeb** [ihavenoface/4chan-x#124] opened 2012-12-30 01:57 UTC
A developer popped in on /g/ announcing he made changes to wordwrapping.
Apparently what he did included inserting [WBRs](https://developer.mozilla.org/en-US/docs/HTML/Element/wbr) into long strings of characters without spaces.
This ends any hyperlinked text prematurely and shift-clicking doesn't fix them either.

**Comment by ihavenoface** [comment] 2012-12-31 15:37
I'll fix this next year. Thanks for reporting.

**Comment by seaweedchan** [comment] 2013-01-06 11:37
I don't see why you can't just fix this now. Just remove all instances of <wbr>

**Comment by ihavenoface** [comment] 2013-01-06 11:48
> Just remove all instances of  <wbr>

You are sure this is safe to do? Then again some stuff isn't done yet so I won't push it to stable just now anyway.

**Comment by seaweedchan** [comment] 2013-01-06 11:54
Its safe to do if you don't care about the three Opera Mobile users using 4chan X with the mobile site, who I think would argue that they'd rather have non-broken links than care about word breaks.

**Comment by seaweedchan** [comment] 2013-01-12 13:00
Poke.

13 days is a long time to go leaving a whole feature of 4chan X broken.

**Comment by skillface** [comment] 2013-01-13 20:57
Still waiting on a fix for this.

**Comment by Poilaucul** [comment] 2013-01-14 17:14
Fix please.

**Comment by ihavenoface** [comment] 2013-01-14 21:17
246aa7daef28eb315c3a272408369c58249e8639 should do the trick for manually concatenating urls.

**Comment by seaweedchan** [comment] 2013-01-15 07:53
Now even that is broken, and concatenating them every time would hardly be a solution anyway.

http://i.imgur.com/G9t3I.png

**Comment by ihavenoface** [comment] 2013-01-15 08:33
What is broken exactly?
The issue isn't closed yet, right?

**Comment by seaweedchan** [comment] 2013-01-15 09:02
Just look at the image. If you try to concatenate the two, nothing will happen at first, and then the TEXT turns into broken link + ENTIRE text good link, with the anchor simply being to the broken link.

**Comment by randyzie** [comment] 2013-01-20 18:03
Curious if this issue has had any more progress.

**Comment by ihavenoface** [comment] 2013-01-20 18:16
@randyzie 
http://rbt.asia/g/thread/30855209

**Comment by randyzie** [comment] 2013-01-20 19:21
Ah, alright thanks.

**Comment by seaweedchan** [comment] 2013-01-22 16:34
Its been 24 days for one little element...

**Comment by ihavenoface** [comment] 2013-01-22 17:30
Then you will be glad to hear that it's making progress.
![142](https://f.cloud.github.com/assets/1175752/87211/aecb7d48-64b8-11e2-8339-50ac901da363.png)

Seriously though, it won't get ready sooner the more often you ask for it. I'm not doing this out of ignorance but because I want to write it right and considering the amount of time I currently have to write on scripts is kind of short this here will eventually delayed even further.

**Comment by ihavenoface** [comment] 2013-01-22 20:26
Here's a compromise for now c46627e69d5d32aecee4f496da3de2b6ed8de619.

**Closed as completed** 2013-04-26 17:26 UTC
Labels: bug
